name: MongsilBot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # ⏰ 30분마다 실행 (예: 12:00, 12:30, 13:00, 13:30 ...)

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Compile and Run Bot
        run: |
          javac MongsilBot.java
          java MongsilBot
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          LLM_URL: ${{ vars.LLM_URL }}
          LLM_KEY: ${{ secrets.LLM_KEY }}
